## <font color="maroon"><h4 align="center">Handling Missing Data - replace method</font>

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("weather_data.csv")
df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Replacing single value**

In [2]:
new_df = df.replace(-99999, value=np.nan)
new_df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Replacing list with single value**

In [3]:
new_df = df.replace(to_replace=[-99999,-88888], value=0)
new_df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Replacing per column**

In [4]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Replacing by using mapping**

In [5]:
new_df = df.replace({
        -99999: np.nan,
        'no event': 'Sunny',
    })
new_df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Regex**

In [6]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True)
new_df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  01/02/2017           35          7  Sunny
2  01/03/2017           28          2   Snow
3  01/04/2017           24          7   Snow
4  01/05/2017           32          4   Rain
5  01/06/2017           31          2  Sunny

**Replacing list with another list**

In [7]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [8]:
#Write the code to replace score from strings to numeric, say poor:1, average:2, good: 3, exceptional: 4

df = df.replace({
    'score': {
        'poor': 1,
        'average': 2,
        'good': 3,
        'exceptional': 4
    }
})

print(df)

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica

C:\Users\binta\AppData\Local\Temp\ipykernel_18156\3615540716.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({

In [9]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica